### ISSUE TITLE
Allow side by side installing of various Maestro versions

### ISSUE THREAD

**Issue by ziemiowid** [jumpinjackie/mapguide-maestro#126]
As a user of Maestro 6.0m10 I fell in following trap: I was able to install Maestro 6.0m11 without any warnings, 
even if I had old (m10) version installed.
Later I noticed that in Maestro's (m11) properties window all paths pointed to old m10 directory. 

It turns out that Maestro m11 reused old configuration folder (`%APPDATA%\Maestro-6.0`)  and it's configuration file.

What's more, currently old configuration files are not deleted when Maestro m10 is uninstalled.
That way, if user do not delete old configuration folder on his own after Maestro is uninstalled,
old (non-existing) paths are passed to newly installed version.

It's hard to tell what problems can have user, who have two versions installed and use them concurrently.

I suppose that if Maestro was using configuration folders named with it's full version name (`Maestro-6.0m11`), it would be possible to install several versions side by side without issues.

**Comment by jumpinjackie** [comment]
Oh yes most definitely the profile folder needs to be more version-specific
