### ISSUE TITLE
New resourrce --> Feature source --> ODBC --> DSN --> select item

### ISSUE THREAD

**Issue by brrmek** [jumpinjackie/mapguide-maestro#127]
Hi, I try to set up a odbc source using a DSN. But the dialogue "Select an item" is empty. The DSN is set up using normal routine. I tested both 32-bit and 64-bit driver without success. Server is Win server 2022 with IIS. And I connect mapguide 4.0.0.9862. ODBC driver is latest from MariaDB.

**Comment by jumpinjackie** [comment]
Thanks for the report. Just a heads up:

I have lots of other dev items on my plate (namely getting the next preview of MapGuide Open Source 4.0 out the door), so don't expect an immediate resolution on this issue.

**Comment by jumpinjackie** [comment]
Cannot reproduce
