### ISSUE TITLE
React Viewer middle mouse scroll button (DragPan) icon stays selected

### ISSUE THREAD

**Issue by Jackson-Percy** [jumpinjackie/mapguide-maestro#135]
**When clicking the middle mouse scroll button (DragPan) it changes to a 'circle with arrows in it' icon, and this will let you pan on the map. However, after doing this doesn't matter what other icons (functions) you click on, on the React Viewer toolbar, or right-clicking on the map it doesn't change the icon back to the selected toolbar function. The functions seem to be selected and working but the icons stay as is.
**

Issue reproduced on the following browsers:
Microsoft Edge, and Google Chrome

MapGuide 4.0.0 Preview 4

MapGuide Maestro Release 6.0m11 (6.0.0.473)

**Comment by jumpinjackie** [comment]
Wrong repo? Moved to: https://github.com/jumpinjackie/mapguide-react-layout/issues/1447
