### ISSUE TITLE
how to connect mapguide maestro to postgres 16? 

### ISSUE THREAD

**Issue by lqmnhakeem217** [jumpinjackie/mapguide-maestro#151]
i been trying to connect my database server which are using postgres 16 to mapguide maestro which i have installed the latest version, but there seem to be an issue with fdo not matching latest version. is there a way to make a custom connection extension that can cater fdo connecting to pg16

**Comment by lqmnhakeem217** [comment]
when i try to logging it require md5 auth but my db use scram-sha-256 auth

**Comment by lqmnhakeem217** [comment]
FDO Connection Status: 
	The remote server returned an error: (559) MgFdoException.: 
An exception occurred in FDO component.
Error occurred in Feature Source (Session:c78f2942-38e1-11ef-8000-a0294205948e_en_MTI3LjAuMC4x0AFC0AFB0AFA//fafbc1bf-6c0c-4fdd-8e23-ee9884b0687a.FeatureSource): An exception occurred in FDO component.
RDBMS: authentication method 10 not supported
 

- MgFdoConnectionManager.Open() line 333 file c:\working\build_area\mapguide\4.0.0\x64\mgdev\server\src\common\manager\FdoConnectionManager.cpp
- MgFdoConnectionManager.CacheFdoConnection() line 1097 file c:\working\build_area\mapguide\4.0.0\x64\mgdev\server\src\common\manager\FdoConnectionManager.cpp
- MgFdoConnectionManager.Open() line 1089 file c:\working\build_area\mapguide\4.0.0\x64\mgdev\server\src\common\manager\FdoConnectionManager.cpp
 (Cause: , Root Cause: )

- MgFeatureServiceHandler.ProcessOperation() line 83 file c:\working\build_area\mapguide\4.0.0\x64\mgdev\server\src\services\feature\FeatureServiceHandler.cpp
- MgOpTestFeatureSourceConnection.Execute() line 100 file c:\working\build_area\mapguide\4.0.0\x64\mgdev\server\src\services\feature\OpTestFeatureSourceConnection.cpp
- MgServerFeatureService.TestConnection() line 245 file c:\working\build_area\mapguide\4.0.0\x64\mgdev\server\src\services\feature\ServerFeatureService.cpp
- MgFdoConnectionManager.Open() line 366 file c:\working\build_area\mapguide\4.0.0\x64\mgdev\server\src\common\manager\FdoConnectionManager.cpp


	The remote server returned an error: (559) MgFdoException. 
 This error generate when i try to add feature source, already tried different services, logins or passwords still not working. Even tried looking into it on the internet but no luck on finding solution to this

**Comment by jumpinjackie** [comment]
It could be that the `libpq.dll` included with the MG/FDO install does not support this authentication type.

If you download a [zip package](https://www.enterprisedb.com/download-postgresql-binaries) of the latest postgresql 16 release and copy `libpq.dll` and dependent dlls to the FDO directory (overwriting existing files). Does this then work?

For the record, this is the full set of dependent dlls you need to copy alongside `libpq.dll` from the latest 16.3 binaries according to  the [Dependencies](https://github.com/lucasg/Dependencies) tool

![2024_07_03_20_37_05_Dependencies_x64_](https://github.com/jumpinjackie/mapguide-maestro/assets/563860/2761da96-6c51-48b5-b04b-59038c96dc3c)

**Comment by lqmnhakeem217** [comment]
Oh, I see. I thought I had already resolved the issue by following this guide: [Error: Unable to load the FDO Provider library 'PostgreSQLProvider.dll' in Map 3D or Civil 3D 2020](https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Error-Unable-to-load-the-FDO-Provider-library-PostgreSQLProvider-dll-in-Map-3D-or-Civil-3D-2020.html).

However, after your suggestion, I noticed some progress. But what does 'FDO Connection Status: False' mean? Does it indicate that my database username and password are incorrect? I am using superuser credentials, so it should work, right?

**Comment by jumpinjackie** [comment]
Not quite sure. MG connection status can obscure the underlying connection failure details.

A better test would be to try creating a PostgresSQL connection with [FDO Toolbox](https://github.com/jumpinjackie/fdotoolbox) with the updated `libpq.dll` and see what happens there.

**Comment by lqmnhakeem217** [comment]
After using [FDO Toolbox](https://github.com/jumpinjackie/fdotoolbox), I've been able to access the database smoothly. However, I'm unsure how to set this up with MapGuide Maestro. Could you provide some guidance on integrating FDO with MapGuide Maestro?

Also, I encountered the following errors in the log files related to the 'FDO Connection Status: False' issue from my previous query:

Error: Problem:\nCannot establish connection to the MapGuide Server.\n\nPossible Causes:\n-Your session has been idle for too long;\n-MapGuide Server is no longer responding;\n-Internet connection problems.\n\nSolution:\nRestart your application / session, restart the MapGuide Server service, or contact with the server administrator

**Comment by jumpinjackie** [comment]
I finally spun up a postgres16 docker image (using https://hub.docker.com/r/kartoza/postgis/) to test this and was able to connect from both MapGuide 4.0 Beta 1 and FDO Toolbox. I also verified this docker image uses `scram-sha-256` auth.

So from this I can only assume your issue was this particular step:

> 2. Backup MapGuide/FDO files and Copy/paste FDOToolBox/FDO files to the MapGuide/FDO files to check if it works (It does not worked)

You did not need to copy *all* the FDO files from FDO Toolbox, you only needed to copy in an updated `libpq.dll` and its dependencies from a postgres16 windows binaries zip file. For ease of reference, this is the full dll list you need to copy from the postgres16 windows binaries.

```
libcrypto-3-x64.dll
libiconv-2.dll
libintl-9.dll
libpq.dll
libssl-3-x64.dll
libwinpthread-1.dll
```
