### ISSUE TITLE
Configuration Document was working with M5 but not M6

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-maestro#36]
http://osgeo-org.1560.x6.nabble.com/MapGuide-Maestro-6-0M6-available-td5306454.html

**Comment by jumpinjackie** [comment]
Who wrote this configuration document? The problem is the document has `fdo:GeometryType` and `fdo:GeometricType` (Note the uppercase G)

Maestro always writes with a lower-case g
