### ISSUE TITLE
Maestro references Bing maps script that no longer exists

### ISSUE THREAD

**Issue by JBurkinshaw** [jumpinjackie/mapguide-maestro#43]
The recent 6.0m7 release initially worked well by allowing an API key to be added for Bing maps. However, the `<VirtualEarthScript>` value of "http://dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=6.2" is referencing a script that no longer exists. More information [here](https://social.msdn.microsoft.com/Forums/en-US/876a50e1-5e36-4eb4-844e-63788f09fe72/api-version-62-not-working?forum=bingmaps).

This causes an error when a Fusion-based template starts up. Chrome developer tools display the following error:

> `Uncaught ReferenceError: VEMapStyle is not defined`

**Comment by jumpinjackie** [comment]
NOTE: You need to use a build of Fusion that supports Bing Maps after the June 30 shutdown of the legacy Bing Maps controls as I've outlined in my blog post: 

https://themapguyde.blogspot.com.au/2017/06/using-bing-maps-heres-some-new-builds.html

Assuming you are indeed using such a build, then from my testing thus far, the `<VirtualEarthScript>` element doesn't appear to be necessary as the OpenLayers Bing layer doesn't appear to be use the script that the `<VirtualEarthScript>` specifies as verified by [this thread](https://social.msdn.microsoft.com/Forums/en-US/50e0e169-2d5e-40c3-bc50-d4bc6be79b67/openlayers-214-and-the-deprecation-of-bing-v7soap?forum=bingmapsservices)

So the only real "bug" I can see on Maestro's end is that it shouldn't be even including the `<VirtualEarthScript>` element anymore, only the specified Bing Maps API key, which it already does.
