### ISSUE TITLE
Specified method is not supported

### ISSUE THREAD

**Issue by gysfyn** [jumpinjackie/mapguide-maestro#48]
I am running mapguide maestro on a Windows 2008 Server and whenever I try to preview a map or a layer, is does not show and returns a error message 'Specified method is not supported'.... Please help me solve this issue.

**Comment by jumpinjackie** [comment]
Where is this error displayed? Do you have screenshots? Stack traces?

**Comment by gysfyn** [comment]
Thanks for the quick response.. 
The error message comes up during the map or layer preview, whilst the display it trying to load.

(I don't have a screen shot now and the problem is at the office pc/server. I am presently at home)

**Comment by gysfyn** [comment]
Please see the error message.

![error msg](https://user-images.githubusercontent.com/19837659/31243104-3128b432-a9d7-11e7-937f-911e50afd27e.jpg)

**Comment by jumpinjackie** [comment]
Are you using MapGuide Open Source 2.0.2 (I can partially see the version number on the Site Explorer)?

I might need to cut off inline preview for anything older than 2.1 (and go back to opening browser windows for previews). The APIs needed for inline preview don't exist in those versions.

**Comment by gysfyn** [comment]
Thanks much. The problem is solved by the response provided.
