### ISSUE TITLE
MGM 6.0m8 / PostgreSQL

### ISSUE THREAD

**Issue by andrerjesus** [jumpinjackie/mapguide-maestro#56]
Hi

I'm migrating MG3.1 from a Windows Server to a CentOS 32 Bits Server.
I have it all installed and configured MG  3.1.0.9064 in the CentOS and  I Installed MGM 6.0.0.223 on my Windows 10 64 bits. Connection when ok, I add my Postgresql 9.6 as a Feature Source and connected ok, but I can not create Vector Layers using that feature source. 

here the error:

> <2017-11-21T13:08:30> 	-1476174992	MapGuide Maestro v6.0.0.223	172.16.34.228	Administrator
>  Error: Invalid repository type.
>  StackTrace:
>   - MgResourceServiceHandler.ProcessOperation() line 80 file ResourceServiceHandler.cpp
>   - MgOpGetResourceHeader.Execute() line 97 file OpGetResourceHeader.cpp
>   - MgServerResourceService.GetResourceHeader() line 1241 file ServerResourceService.cpp	

I tried using MGM 6.0.0.63 and I could create the feature source and the vector layer, I guess It has a bug in the 223 build

MGM 6.0m7 (60.0.0.82) works fine

**Comment by jumpinjackie** [comment]
I strongly suspect this is the same as #58

**Comment by andrerjesus** [comment]
Sorry to reopen this issue but this is another bug:

- **Does not save user password after the admin session is closed.**
-- FATAL:  password authentication failed for user "mg_user_db"

- **MG uses the user name as database name and tries the first connection**
-- FATAL:  database "mg_user_db" does not exist

- **It requires MG to have access to topology schema**
-- ERROR:  permission denied for schema topology at character 356
-- STATEMENT:  SELECT l.table_name,l.schema_name,l.feature_column,CASE WHEN l.feature_type = 1 THEN 'MULTIPOINT' WHEN l.feature_type = 2 THEN 'MULTILINESTRING' WHEN l.feature_type = 3 THEN 'MULTIPOLYGON' WHEN l.feature_type = 4 THEN 'GEOMETRYCOLLECTION' END AS type,(SELECT srid FROM topology.topology t WHERE l.topology_id=t.id),2,c.relkind,obj_description(c.oid) FROM topology.layer l,pg_class c,pg_namespace n WHERE c.relname=l.table_name AND l.schema_name=n.nspname AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND l.schema_name='public' ORDER BY n.nspname,c.relname,l.feature_column

- **It requires MG to have access to pg_authid table**
-- ERROR:  permission denied for relation pg_authid
-- STATEMENT:  DECLARE fdo7 CURSOR FOR  SELECT  t.table_schema  || '.' || t.table_name AS name,  lower(t.table_type) AS type,  convert_to(t.table_schema,'UTF8') as collate_schema_name,  convert_to(t.table_name,'UTF8') as collate_table_name  FROM information_schema.tables AS t   WHERE t.table_schema not in ( 'information_schema' ,'pg_catalog')    AND t.table_type IN ('BASE TABLE','VIEW')  AND t.table_name not in ( 'geometry_columns', 'geography_columns','spatial_ref_sys', 'raster_columns', 'raster_overviews')  UNION  SELECT ns.nspname || '.' || c.relname AS name,  'view' AS type,  convert_to(ns.nspname,'UTF8') AS collate_schema_name,  convert_to(c.relname,'UTF8') AS collate_table_name  FROM pg_class AS c  JOIN pg_authid o ON c.relowner = o.oid  JOIN pg_namespace ns ON c.relnamespace = ns.oid  WHERE c.relkind = 'm'  ORDER BY collate_schema_name, collate_table_name ASC 

- **Wrong syntax**
-- ERROR:  syntax error at or near "STATEMENT" at character 1
-- STATEMENT:  STATEMENT:  SELECT l.table_name,
	-- l.schema_name,
	-- l.feature_column,
	-- CASE 
	-- WHEN l.feature_type = 1 THEN 'MULTIPOINT' 
	-- WHEN l.feature_type = 2 THEN 'MULTILINESTRING' 
	-- WHEN l.feature_type = 3 THEN 'MULTIPOLYGON' 
	-- WHEN l.feature_type = 4 THEN 'GEOMETRYCOLLECTION' END AS type,
	-- (SELECT srid FROM topology.topology t WHERE l.topology_id=t.id),
	-- 2,
	-- c.relkind,
	-- obj_description(c.oid) FROM topology.layer l,
	-- pg_class c,
	-- pg_namespace n WHERE c.relname=l.table_name AND l.schema_name=n.nspname AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,
	-- 'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"',
	-- 'select') AND l.schema_name='public' ORDER BY n.nspname,
	-- c.relname,
	-- l.feature_column

I guess the main problem is that MapGuide is not keeping the user authentication after the session is closed either for timeout out or close the app.

**Comment by jumpinjackie** [comment]
Regarding pg_authid: https://trac.osgeo.org/fdo/ticket/949
