### ISSUE TITLE
Fusion Error

### ISSUE THREAD

**Issue by hirdajoe** [jumpinjackie/mapguide-maestro#66]
Hi, can you help with the fusion error?
1. I've also encountered problems in buffer, it didn't pop up when clicked. 
2. Search button/task in custom command where the button didn't exist in the maps.
3.  Public URL in Application Definition didn't work, I have to use the preview link.

Below are the error in Fusion I got.
Thanks.

Error Details:
Exception occurred in AJAX callback.
Message: Cannot read property 'message' of undefined
Location: undefined (undefined)
Inner Stack: TypeError: Cannot read property 'message' of undefined
    at Object.ajaxException (http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js:32:436)
    at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js:1171:474
    at initialize.respondToReadyState (http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js:2057:515)
    at initialize.onStateChange (http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js:2055:426)
    at XMLHttpRequest. (http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js:1171:474)
Response: 

Stack Trace:
 - ? at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 54)
 - Object.ajaxException at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 32)
 - ? at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 1171)
 - initialize.respondToReadyState at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 2057)
 - initialize.onStateChange at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 2055)
 - XMLHttpRequest. at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 1171)
 - Object.ajaxException at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 32)
 - ? at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 1171)
 - initialize.dispatchException at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 2058)
 - initialize.respondToReadyState at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 2057)
 - initialize.onStateChange at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 2055)
 - XMLHttpRequest. at http://localhost:8008/mapguide/fusion/lib/fusionSF-compressed.js (line: 1171)

Source:
http://localhost:8008/mapguide/fusion/templates/mapguide/slate/index.html?Session=386bbdaa-5730-11e8-8000-2016d8f0c4a3_en_MTI3LjAuMC4x0AFC0AFB0AFA&ApplicationDefinition=Session:386bbdaa-5730-11e8-8000-2016d8f0c4a3_en_MTI3LjAuMC4x0AFC0AFB0AFA//a70898e6-f9a5-4ae3-ab27-48284774d6c0.ApplicationDefinition&locale=en

**Comment by jumpinjackie** [comment]
Not related to Maestro at all. Closing.
